### PR TITLE
Adds linux build spec

### PR DESCRIPTION
**Pull request by domna**
This adds a linux build spec and a small fix for the logo. See #33 for a discussion.

@kaixxx @gernophil: I have a binary file now. How are you distributing it? I think it would also be possible to make a github action to automatically build these on commit/release as in https://github.com/kaixxx/noScribeEditor/pull/2

### CODE REVIEW

**Comment by kaixxx** [comment]
Thank you very much. I'm not a regular linux user (at least not on my desktop). But I've heard about [flatpak](https://www.flatpak.org/) as a new way to distribute apps accross different linux distributions. What do you think, would this be a way to go?

**Comment by domna** [comment]
> Thank you very much. I'm not a regular linux user (at least not on my desktop). But I've heard about [flatpak](https://www.flatpak.org/) as a new way to distribute apps accross different linux distributions. What do you think, would this be a way to go?

Could be. But I'm not really using linux in my production system, too. Also I'm not really experienced in linux packaging (+ the state of the art of it) and there seem to be a lot of competing distribution agnostic packaging solutions nowadays. If someone would like to create such a package it should be easily possible from the binary files I created, but I don't really have the time to dig into this myself. However, it should also be possible to just download and run the binary file if it's offered for download somewhere (since creating the binary _is_ basically creating a package - normally linux would use shared libraries and such).

**Comment by kaixxx** [comment]
Ok, so lets share the binary. Do you think it will run on different distros? On which distro are you building?
Please send me an Email to kai.droege [aaatttt] hslu.ch so that I can give you access to a shared folder on switch drive, a filesharing platform for swiss universities. This is where I distribute noScribe.

**Comment by domna** [comment]
> Ok, so lets share the binary. Do you think it will run on different distros? On which distro are you building? Please send me an Email to kai.droege [aaatttt] hslu.ch so that I can give you access to a shared folder on switch drive, a filesharing platform for swiss universities. This is where I distribute noScribe.

Yes, I think it will be no problem to run it on different distros. The shared libraries are all included by pyinstaller so there is virtual no difference between different distros as long as the architecture matches (but this is also true for windows I guess). I build on fedora but I also created a Dockerfile now to create this on any system.

**Pull request merged**
