### PR TITLE
Linux support (rebased to latest version)

### PR DESCRIPTION
**Pull request by domna**
This adds linux support for the latest version (based on #23) and integrates the ML models as git submodules.

ToDo:
- [x] Fix link at the end of transcription process

### CODE REVIEW

**Comment by domna** [comment]
Sure, git submodules are essentially a git repository referred inside your repository (since the huggingface models are also git repositories). [Here](https://git-scm.com/book/en/v2/Git-Tools-Submodules) is a short summary from the git documentation. There are advantages but also some disadvantages of using submoduling in a project.

The benefits are that the files in the submodules are integrated as if they where copied directly in these folders (i.e., the exact thing you describe in prior the download.txt files) and they keep the whole commit history of the referred submodule + refer to a certain fixed commit, so when the remote git repo update it stays at this commit ensuring that your software still works even if something changed remotely.
Disadvantages are that submodules are a bit more overhead to work with, you have to add `--recurse-submodules` when cloning the repo or invoke a `git submodule init ...` command to update them. Additionally, since the huggingface repositories you are referring to here use [git lfs](https://git-lfs.com) (for *l*arge *f*ile *s*upport, TL;DR: One should not store large files in a git repo because this pollutes the versioning and blows up the .git folder, git lfs replaces larges file with an external reference effectively taking them partly out of the version control) you also need to add this to your git which complicates the situation further.

So it's your consideration whether you want to use it in this repository. I just introduced them because I think it's a good use case for submodules, but I'm also used to working with submodules so I understand if it complicates the situation too much (in that case I can remove the submoduling from this PR if you like).

**Comment by domna** [comment]
This PR has still one shortcoming: The link at the end of the transcription does not work with noScribeEdit yet. I probably will first fall back to simply opening the html page in a browser and see if I can get noScribeEdit to work on Linux. I could also envision integrating noScribeEdit as a submodule if you like the idea of working with submodules (that way it would not be necessary to use the command but it could rather be spawned from the python code directly, which would practically make it platform independent).

**Comment by kaixxx** [comment]
Thank you for the explanation regarding submodules. Your approach makes sense in the current situation. But for the future, there is a good chance that we will deviate from the official repo of faster-whisper and host our own models somewhere else. Even right now, the installer of noScribe already ships with a quantized version of the “small” model that is not in the official repo (you can still use the original model no problem, it’s just a bit bigger). In essence, I would rather not use submodules to stay flexible. 

Regarding noScribeEdit: It would be great if you could get this running on Linux too. Having an easy way of controlling and correcting the transcripts is very important and was a crucial consideration for me from the very beginning of developing noScribe. One reason for switching from Word-Macros to my own editor (with v.0.4) was to make this correction function more accessible for people who are not using proprietary software. 
Right now, the integration of noScribeEdit is a bit hacky: We compile it as a separate app (using pyinstaller) and copy the resulting binaries in the subfolder “noScribeEdit” in the main app folder (at least this is how I do it on windows). 
If you want to start the editor not as a binary but from its python source, you must implement this in the “launch_editor” function somehow. I would still like to keep the editor an independent app that can also be used separate from the main noScribe.

**Comment by domna** [comment]
> Thank you for the explanation regarding submodules. Your approach makes sense in the current situation. But for the future, there is a good chance that we will deviate from the official repo of faster-whisper and host our own models somewhere else. Even right now, the installer of noScribe already ships with a quantized version of the “small” model that is not in the official repo (you can still use the original model no problem, it’s just a bit bigger). In essence, I would rather not use submodules to stay flexible.

If this is your only concern I think you can also do fine with the submodule approach. You can just add your own models as a submodule (currently the large and small model also live side to side in their own submodules), replace the old ones or add your own data as a download. Actually, that's what submodules are partially build for: to have a drop in replacement in a particular folder (just change the submodule and you're good to go. At least when the structure matches). As far as I see it you can change between the two models in the GUI, right? So you could also build a `json` or `yaml` file relating these entries to the model folders and then noScribe just picks the right folder. This way it would work for any model you would like to add. But that's also somewhat independent of using submodules as they really just checking out a git repo in a folder. So just let me know with what you'd like to go and I'll keep or remove the submodules based on your decision (I would add a script for downloading them if we don't keep the submodules though - I'm too lazy for manually downloading things 😅).
> 
> Regarding noScribeEdit: It would be great if you could get this running on Linux too. Having an easy way of controlling and correcting the transcripts is very important and was a crucial consideration for me from the very beginning of developing noScribe. One reason for switching from Word-Macros to my own editor (with v.0.4) was to make this correction function more accessible for people who are not using proprietary software. Right now, the integration of noScribeEdit is a bit hacky: We compile it as a separate app (using pyinstaller) and copy the resulting binaries in the subfolder “noScribeEdit” in the main app folder (at least this is how I do it on windows). If you want to start the editor not as a binary but from its python source, you must implement this in the “launch_editor” function somehow. I would still like to keep the editor an independent app that can also be used separate from the main noScribe.

Yes, I just quickly tried to get it to run on linux yesterday and wasn't even aware of the `noScribeEdit` package. I only found out about it when I tried to click the link. Currently, I just spawn a webbrowser showing the html page if noScibeEdit could not  be found. I think that's a good fallback behaviour even if noScibeEdit is not installed for whatever reason.

I think porting noScribeEdit to linux will be straightforward. I only had a quick look, but it's already running. Only the conversion fails because there is no linux `ffmpeg` binary. So I think I just have to add this and add the appropriate os checks in the code.

Regarding the submoduling or using directly from python code: I think `noScribeEdit` can be used as is directly from python without changing anything in the repo structure. So it still can be supplied as a standalone package. I think the cleanest way would be plugin [`entry_points`](https://setuptools.pypa.io/en/latest/userguide/entry_point.html#entry-points-for-plugins) to load `noScribeEdit` as a plugin in `noScribe`. Do you have plans to provide `noScribe` and `noScribeEdit` as python packages? (There are also [`gui-scripts`](https://setuptools.pypa.io/en/latest/userguide/entry_point.html#gui-scripts) which generate a binary/exe file automatically for you).

I would suggest that I give porting `noScribeEdit` to linux a shot and would keep this PR for review as is (except the submoduling which I will adapt to what you decide). When I get noScribeEdit to work I'll make a separate PR in the noScribeEdit and this repo to re-enable the behaviour. Sounds good?

**Comment by kaixxx** [comment]
Hosting models elsewhere as a submodul would mean hosting them on some kind of git server, which is not trivial given the size of the files. 
For noScribeEdit, submoduling could make more sense. But we had a lot of trouble getting the packaging (+ signing and notarization on macOS) with pyinstaller to work. So I would rather not mess with the structure of the project if not absolutely necessary. 
Overall, I think using submodules is a bit complicated right now, so I would be happy if you could remove this from your commit if you are ok with that. I will keep the idea in the back of my mind for a potential future refactoring of the code.
 
Other than that, your suggestion sounds good. Using the webrowser as a fallback for viewing is a good idea. But please add a message box explaining that noScribe comes with it's own editor to review and correct the transcript and how people can install it (or, for the time beeing, that this editor will become available on Linux soon).

**Comment by kaixxx** [comment]
> Do you have plans to provide noScribe and noScribeEdit as python packages?

No, not really. Right now, noScribe is mainly targeted at not so tech-savy people (qualitative researchers and journalists in particular). But maybe there are other use cases? May I ask what you are planing to do with noScribe? You seem to come from a quite different field (but also from Frankfurt, funny enough).

**Comment by domna** [comment]
> Overall, I think using submodules is a bit complicated right now, so I would be happy if you could remove this from your commit if you are ok with that. I will keep the idea in the back of my mind for a potential future refactoring of the code.

Yes, no problem. I'll revert it to the previous state.

> Other than that, your suggestion sounds good. Using the webrowser as a fallback for viewing is a good idea. But please add a message box explaining that noScribe comes with it's own editor to review and correct the transcript and how people can install it (or, for the time beeing, that this editor will become available on Linux soon).

Yes, I can certainly add this.

> No, not really. Right now, noScribe is mainly targeted at not so tech-savy people (qualitative researchers and journalists in particular). But maybe there are other use cases? May I ask what you are planing to do with noScribe? You seem to come from a quite different field (but also from Frankfurt, funny enough).

Actually, I'm just helping out a friend who needed to run the software on a linux system. But I think noScribe is a nice project and seems really helpful for leveraging such ML models for a wider audience that I thought that I make it a proper contribution instead of just hacking it together :).
And yes I'm coming from a very different field in natural sciences and programming.

**Comment by domna** [comment]
Hey @kaixxx, I removed the submoduling and added a call for noScribeEdit. There is a pull request as well which adds the necessary changes to let it run under linux.

**Comment by kaixxx** [comment]
This looks nice, thank you. Please give us a few days to review the code and test it on the various platforms. 

One note: It seems that you had problems loading the logo icon under linux. There is also a png-version in the repo. You may try using that.

**Comment by domna** [comment]
Thanks for the note. I actually just carried this part over from #23 and @eckhrd's work and did not check it myself. But I will give the png a shot, if it works I'll just use this. Should the png then generally be used also for macOS and Win or do you prefer the ico there?

**Comment by kaixxx** [comment]
> Should the png then generally be used

No, I think we'll stick with the ico for Windows and MacOS. "Never change a working icon", you know...

**Comment by domna** [comment]
Works with png 👍️

**Comment by kaixxx** [comment]
@domna Forgot something: Do you have binaries for us to share?

**Comment by menelic** [comment]
This is great news, thanks for the work on this - but please create a new release with install instructions, I am not clear if the current main branch can be installed on linux?

**Comment by domna** [comment]
> @domna Thank you again for the great work. I have merged the PR with minor adjustments.
> 
> One last thing for now: Could you write some short installation instructions for Linux? See this section of the Readme: https://github.com/kaixxx/noScribe#download-and-installation

Actually, I just ran python directly in the repo and didn't create any binary. This should be sufficient for running it:
```
git clone https://github.com/kaixxx/noScribe.git
cd noScribe
pip install -r environments/requirements-linux.txt
python noScribe.py
```
It should work for any python version noScribe supports and is ideally done in a new environment. For noScribeEditor, this has of course to be build by itself and put into the correct location.

I'll try to create an installer with pyinstaller and provide it. It will take some time though as I don't have too much time to work on this right now (but until then the above install instructions should help) and I don't have any experience with pyinstaller.

**Comment by kaixxx** [comment]
@domna: I've got quite a few requests over the last couple of weeks from people interested in running noScribe on Linux. I always point them to your instructions above. But not all of them are comfortable running python etc. 

So it would be absolutely wonderful if you could find the time to make a binary...

**Comment by menelic** [comment]
@domna thank you for the Linux script - I d like to respectfully request yeta notehr step owards easy usage on linux:  an appimage and/or flatpack or even a snap would also be greatly appreciated. AppImages to me seem the best solution distro-agnostic, package their dependencies and cal easily be updated. Unlike flatpack or snap they don't require anything else to be installed to work (that said I do see the advantages of flatpack)
@kaixxx looks like appimage creation can be automated here on Github, once the recipe is implemented https://appimage-builder.readthedocs.io/en/latest/intro/tutorial.html and https://www.reddit.com/r/AppImage/comments/xmgvmx/just_created_my_first_github_action_to_automate/

**Comment by kaixxx** [comment]
@domna: Thank you! We had a few problems with the most recent version on Linux, but they seem to be resolved, see: https://github.com/kaixxx/noScribe/discussions/60

**Comment by domna** [comment]
> @domna thank you for the Linux script - I d like to respectfully request yeta notehr step owards easy usage on linux: an appimage and/or flatpack or even a snap would also be greatly appreciated. AppImages to me seem the best solution distro-agnostic, package their dependencies and cal easily be updated. Unlike flatpack or snap they don't require anything else to be installed to work (that said I do see the advantages of flatpack)

Hey @menelic,

sorry I don't really have time to create such a package as I'm not really experienced with that, so I would need to learn the whole process of it. However, I contributed a build spec for binary files now https://github.com/kaixxx/noScribe/pull/63 and once this is distributed somewhere you should be able to download and run noScribe easily. I think it would be easy to use this as a basis for an appimage or flatpak if someone would be interested in creating and maintaining this.

**Pull request merged**
