### PR TITLE
Update noScribe.pyw

### PR DESCRIPTION
**Pull request by yjeanrenaud**
added -hwaccel auto in ffmpeg_cmd to make use of a little acceleration by GPU/CUDA/MMX/etc.

### CODE REVIEW

**Comment by kaixxx** [comment]
Nice, thank you! I'm going to accept this, but please be patient. I'm working with somebody on getting a version for macOS ready and try to avoid adding new features until then.

**Comment by antonioaraujo664** [comment]
Can you teach me how to compile? I want to get more performance using my RTX 3060. Please. I promise to make a donation.

**Comment by kaixxx** [comment]
>  I want to get more performance using my RTX 3060.

There is a new CUDA-version in development: https://github.com/kaixxx/noScribe/discussions/50 Please test and report back!

**Comment by kaixxx** [comment]
@yjeanrenaud 
Hi Yves, it took quite a while, but I have now included your suggestion here: https://github.com/kaixxx/noScribe/commit/6d21f80439a8e4c8765d4af56733f33f0264be5b
It's probably going to make only a small difference in overall processing time, but every second counts ;)

**Pull request closed without merging**
